-- =============================================================================
-- 마이그레이션 · 2026-09 · 주차 → 섹션 · 레슨, 시청 시간, 레슨별 과제 · 자료
--
-- 이미 돌아가는 DB(라이브)에 적용한다. db/schema.sql 은 DROP+CREATE 라 데이터를 지우므로
-- 라이브에는 이 파일을 쓴다 — psql "$DATABASE_URL"(5432 직접 연결) -v ON_ERROR_STOP=1 -f 이 파일.
--
-- 규칙
--   · 옛 표 · 컬럼(ext_week · ext_mission · lounge_week · post.week · lounge_member.week ·
--     ext_lesson.week/chapter/duration)은 지우지 않는다. 한 릴리스 뒤에 지운다.
--   · 확인 질의가 0 이 아니면 트랜잭션을 멈춘다(RAISE). 반쯤 옮긴 상태로 커밋되지 않는다.
--   · 과제(ext_mission)는 그 섹션의 **마지막 레슨**에 붙는다 — 주차를 다 듣고 내는 과제였다.
-- =============================================================================

BEGIN;

-- ---------------------------------------------------------------- 1. 타입 · 새 표
DO $$ BEGIN
  CREATE TYPE material_kind AS ENUM ('file', 'link');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS ext_section (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint       NOT NULL,
  seq       smallint     NOT NULL,
  title     varchar(200) NOT NULL,
  synced_at timestamptz,
  UNIQUE (course_id, seq)
);

CREATE TABLE IF NOT EXISTS lesson_task (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  lounge_id  bigint       NOT NULL REFERENCES lounge (id),
  lesson_id  bigint       NOT NULL,
  seq        smallint     NOT NULL DEFAULT 1,
  title      varchar(200) NOT NULL,
  questions  jsonb        NOT NULL,
  created_at timestamptz  NOT NULL DEFAULT now(),
  updated_at timestamptz  NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_task_lesson ON lesson_task (lounge_id, lesson_id, seq) WHERE deleted_at IS NULL;
DROP TRIGGER IF EXISTS task_touch ON lesson_task;
CREATE TRIGGER task_touch BEFORE UPDATE ON lesson_task
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE IF NOT EXISTS lesson_material (
  id         bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  lounge_id  bigint        NOT NULL REFERENCES lounge (id),
  lesson_id  bigint        NOT NULL,
  seq        smallint      NOT NULL DEFAULT 0,
  kind       material_kind NOT NULL,
  url        varchar(1000) NOT NULL,
  label      varchar(300),
  created_at timestamptz   NOT NULL DEFAULT now(),
  deleted_at timestamptz
);
CREATE INDEX IF NOT EXISTS ix_material_lesson ON lesson_material (lounge_id, lesson_id, seq) WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS lounge_section (
  lounge_id  bigint      NOT NULL REFERENCES lounge (id),
  section_id bigint      NOT NULL,
  published  boolean     NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (lounge_id, section_id)
);

-- ---------------------------------------------------------------- 2. 컬럼 추가
ALTER TABLE ext_lesson
  ADD COLUMN IF NOT EXISTS section_id   bigint,
  ADD COLUMN IF NOT EXISTS duration_sec integer,
  ADD COLUMN IF NOT EXISTS description  text,
  ADD COLUMN IF NOT EXISTS timeline     jsonb;
ALTER TABLE ext_lesson ALTER COLUMN week DROP NOT NULL;
ALTER TABLE ext_lesson ALTER COLUMN seq  DROP NOT NULL;

ALTER TABLE ext_watch     ADD COLUMN IF NOT EXISTS watched_sec integer NOT NULL DEFAULT 0;
ALTER TABLE post          ADD COLUMN IF NOT EXISTS task_id bigint REFERENCES lesson_task (id);
ALTER TABLE lounge_member ADD COLUMN IF NOT EXISTS section_id bigint,
                          ADD COLUMN IF NOT EXISTS section_synced_at timestamptz;

-- ---------------------------------------------------------------- 3. 주차 → 섹션
INSERT INTO ext_section (course_id, seq, title, synced_at)
SELECT w.course_id, w.week, w.title, w.synced_at
  FROM ext_week w
 WHERE NOT EXISTS (SELECT 1 FROM ext_section s WHERE s.course_id = w.course_id AND s.seq = w.week)
 ORDER BY w.course_id, w.week;

-- 주차 행이 없는데 레슨만 있는 주차는 'N주차' 제목으로 보충한다
INSERT INTO ext_section (course_id, seq, title, synced_at)
SELECT DISTINCT l.course_id, l.week, l.week || '주차', now()
  FROM ext_lesson l
 WHERE l.week IS NOT NULL
   AND NOT EXISTS (SELECT 1 FROM ext_section s WHERE s.course_id = l.course_id AND s.seq = l.week);

-- ---------------------------------------------------------------- 4. 레슨
UPDATE ext_lesson l
   SET section_id = s.id
  FROM ext_section s
 WHERE s.course_id = l.course_id AND s.seq = l.week AND l.section_id IS NULL;

UPDATE ext_lesson
   SET duration_sec = split_part(duration, ':', 1)::int * 60 + split_part(duration, ':', 2)::int
 WHERE duration_sec IS NULL AND duration ~ '^\d+:\d{2}$';

UPDATE ext_lesson SET timeline = '[]'::jsonb WHERE timeline IS NULL;

DO $$ DECLARE n int; BEGIN
  SELECT count(*) INTO n FROM ext_lesson WHERE section_id IS NULL;
  IF n > 0 THEN RAISE EXCEPTION '섹션이 없는 레슨 %건', n; END IF;
END $$;

ALTER TABLE ext_lesson ALTER COLUMN section_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS ix_lesson_section ON ext_lesson (section_id, seq);
CREATE INDEX IF NOT EXISTS ix_lesson_trgm_desc ON ext_lesson USING gin (description gin_trgm_ops);
-- 같은 섹션 안에서 seq 가 유일해야 한다. 옛 UNIQUE(course_id, week, seq) 는 둔다 — 지우는 릴리스에서
DO $$ BEGIN
  ALTER TABLE ext_lesson ADD CONSTRAINT ext_lesson_section_id_seq_key UNIQUE (section_id, seq);
EXCEPTION WHEN duplicate_table OR duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------- 5. 미션 → 과제 (섹션 마지막 레슨에 하나)
INSERT INTO lesson_task (lounge_id, lesson_id, seq, title, questions)
SELECT lg.id, ll.id, 1, min(m.title),
       jsonb_agg(jsonb_build_object('q', m.question, 'hint', m.hint) ORDER BY m.seq)
  FROM ext_mission m
  JOIN lounge lg      ON lg.course_id = m.course_id
  JOIN ext_section s  ON s.course_id = m.course_id AND s.seq = m.week
  JOIN LATERAL (SELECT id FROM ext_lesson WHERE section_id = s.id ORDER BY seq DESC LIMIT 1) ll ON true
 WHERE NOT EXISTS (SELECT 1 FROM lesson_task t WHERE t.lounge_id = lg.id AND t.lesson_id = ll.id)
 GROUP BY lg.id, ll.id, m.course_id, m.week;

-- ---------------------------------------------------------------- 6. 과제 글 → task_id
UPDATE post p
   SET task_id = t.id
  FROM lesson_task t
  JOIN ext_lesson l  ON l.id = t.lesson_id
  JOIN ext_section s ON s.id = l.section_id
  JOIN category c    ON c.name = '과제'
 WHERE t.lounge_id = p.lounge_id
   AND s.seq = p.week
   AND p.category_id = c.id
   AND p.week IS NOT NULL
   AND p.task_id IS NULL;

DO $$ DECLARE n int; BEGIN
  -- 주차는 있는데 과제로 못 옮긴 과제 글. 그 주차에 미션이 없었던 것이다 — 있으면 사람이 봐야 한다
  SELECT count(*) INTO n FROM post p JOIN category c ON c.id = p.category_id
   WHERE c.name = '과제' AND p.week IS NOT NULL AND p.task_id IS NULL AND p.deleted_at IS NULL;
  IF n > 0 THEN RAISE EXCEPTION '과제로 옮기지 못한 과제 글 %건', n; END IF;

  -- 한 사람이 같은 과제에 살아 있는 글을 둘 이상 갖고 있으면 유니크가 막힌다. 오래된 것을 지운다.
  UPDATE post p SET deleted_at = now()
   WHERE p.task_id IS NOT NULL AND p.deleted_at IS NULL
     AND EXISTS (SELECT 1 FROM post q WHERE q.task_id = p.task_id AND q.user_id = p.user_id
                                        AND q.deleted_at IS NULL AND q.created_at > p.created_at);
END $$;

CREATE INDEX IF NOT EXISTS ix_post_task ON post (lounge_id, task_id, user_id) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_post_task_user ON post (task_id, user_id) WHERE task_id IS NOT NULL AND deleted_at IS NULL;

-- ---------------------------------------------------------------- 7. 시청 시간 · 섹션 게시 · 멤버 섹션
UPDATE ext_watch w SET watched_sec = l.duration_sec
  FROM ext_lesson l
 WHERE l.id = w.lesson_id AND w.is_complete AND l.duration_sec IS NOT NULL AND w.watched_sec = 0;

INSERT INTO lounge_section (lounge_id, section_id, published, updated_at)
SELECT lw.lounge_id, s.id, lw.published, lw.updated_at
  FROM lounge_week lw
  JOIN lounge lg     ON lg.id = lw.lounge_id
  JOIN ext_section s ON s.course_id = lg.course_id AND s.seq = lw.week
ON CONFLICT (lounge_id, section_id) DO NOTHING;

UPDATE lounge_member m
   SET section_id = s.id, section_synced_at = now()
  FROM lounge lg, ext_section s
 WHERE lg.id = m.lounge_id AND s.course_id = lg.course_id
   AND s.seq = least(coalesce(m.week, 1), (SELECT max(seq) FROM ext_section x WHERE x.course_id = lg.course_id))
   AND m.section_id IS NULL;

CREATE INDEX IF NOT EXISTS ix_member_section ON lounge_member (lounge_id, section_id);

-- ---------------------------------------------------------------- 8. 요약
DO $$ DECLARE r record; BEGIN
  SELECT (SELECT count(*) FROM ext_section) AS sections,
         (SELECT count(*) FROM ext_lesson WHERE section_id IS NOT NULL) AS lessons,
         (SELECT count(*) FROM lesson_task) AS tasks,
         (SELECT count(*) FROM post WHERE task_id IS NOT NULL AND deleted_at IS NULL) AS task_posts,
         (SELECT count(*) FROM lounge_section) AS flags,
         (SELECT count(*) FROM lounge_member WHERE section_id IS NOT NULL) AS members
    INTO r;
  RAISE NOTICE '섹션 % · 레슨 % · 과제 % · 과제 글 % · 게시 플래그 % · 섹션 있는 멤버 %',
    r.sections, r.lessons, r.tasks, r.task_posts, r.flags, r.members;
END $$;

COMMIT;
