-- 샘플 라운지(lounge 1)의 레슨에 영상 · 설명란 · 타임라인 · 교안 샘플을 채운다. web/assets/data-mock.js 가 원본.
-- 라이브: psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -q -f db/patch-sample-lesson-content.sql
BEGIN;
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:43 고객 정의 · 3:26 정리', timeline='[{"t":0,"label":"인트로"},{"t":103,"label":"고객 정의"},{"t":206,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='여러분 학원의 주인공은 어떤 아이입니까. 그리고 뒤집어서, 안 받을 학생을 말할 수 있습니까. 학생을 정하면 학부모도 정해집니다. 그 학부모가 밤에 무엇을 검색하고, 상담 전화에서 무엇을 차마 못 묻는지까지 따라옵니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=1 AND l.seq=1 AND l.title='우리 학원의 주인공은 누구인가';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:30 경쟁사 분석 · 3:00 정리', timeline='[{"t":0,"label":"인트로"},{"t":90,"label":"경쟁사 분석"},{"t":180,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='우리 동네 학원 다섯 곳의 소개글을 나란히 놓으면 이름을 가려도 구분이 됩니까. 경쟁 분석의 목적은 이기는 게 아니라 빈자리를 찾는 것입니다. 다들 상위권과 소수정예를 외칠 때 아무도 안 서 있는 자리는 어디인가.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=1 AND l.seq=2 AND l.title='옆 학원은 뭐라고 말하고 있는가';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 2:06 여섯 문장 공식 · 4:13 문장별 예시', timeline='[{"t":0,"label":"인트로"},{"t":126,"label":"여섯 문장 공식"},{"t":253,"label":"문장별 예시"}]'::jsonb, doc='타겟 선언, 진짜 문제, 우리의 방법, 증거, 차별점 한 방, 다음 행동 제안. 여섯 문장이 전부 주인공 정의에서 흘러나옵니다. 이 여섯 문장이 이후 블로그와 인스타와 상담 멘트의 기초가 됩니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=1 AND l.seq=3 AND l.title='학원 소개 6문장 쓰기';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:25 검색 여정 · 2:50 정리', timeline='[{"t":0,"label":"인트로"},{"t":85,"label":"검색 여정"},{"t":170,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='소개받은 학부모도 등록 전에 반드시 하는 행동이 있습니다. 검색입니다. 검색에서 플레이스 목록, 사진과 리뷰 훑기, 블로그 확인, 그리고 문의. 이 여정의 각 단계마다 학부모가 이탈합니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=2 AND l.seq=1 AND l.title='학부모는 어떤 경로로 학원을 찾는가';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:21 플레이스 · 2:43 정리', timeline='[{"t":0,"label":"인트로"},{"t":81,"label":"플레이스"},{"t":163,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='상위노출을 결정하는 요소들. 소개글은 새로 쓰는 게 아니라 1주차 여섯 문장을 축약해서 붙이는 것입니다. 사진은 학부모가 확인하고 싶은 것 순서대로 공간, 수업, 아이들. 리뷰는 요청하는 법과 답글 다는 법.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=2 AND l.seq=2 AND l.title='플레이스 전면 재세팅';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:26 키워드 · 2:53 정리', timeline='[{"t":0,"label":"인트로"},{"t":86,"label":"키워드"},{"t":173,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='학부모는 학원 소식을 검색하지 않습니다. 1주차 주인공 학부모가 밤에 검색하는 말들이 곧 키워드입니다. 지역 키워드와 고민 키워드 두 갈래로 모읍니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=3 AND l.seq=1 AND l.title='학부모는 블로그에서 무엇을 검색하는가';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:38 블로그 3종 세트 · 3:16 정리', timeline='[{"t":0,"label":"인트로"},{"t":98,"label":"블로그 3종 세트"},{"t":196,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='소개하기는 1주차 여섯 문장을 글 한 편으로 풀어낸 것입니다. 학부모 질문 TOP 10은 상담 전화에서 실제로 받는 질문에 미리 답하기. 고객의 언어는 학부모가 차마 못 묻는 걱정을 먼저 꺼내서 답하기.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=3 AND l.seq=2 AND l.title='블로그 3종 세트 — 이것부터 쓰면 된다';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:21 다섯 기둥 · 2:43 분류 연습', timeline='[{"t":0,"label":"인트로"},{"t":81,"label":"다섯 기둥"},{"t":163,"label":"분류 연습"}]'::jsonb, doc='전문가로 실력을 증명하고, 철학으로 왜 이렇게 가르치는지 말하고, 증거로 변화 사례와 후기를 쌓고, 신뢰로 일상과 사람 냄새를 내고, 상품으로 모집과 안내를 합니다. 다섯 중 어디에도 안 들어가면 안 올려도 됩니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=3 AND l.seq=3 AND l.title='콘텐츠 5기둥 — 올리는 모든 것의 분류함';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:16 프로필 · 2:33 정리', timeline='[{"t":0,"label":"인트로"},{"t":76,"label":"프로필"},{"t":153,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='학부모는 피드를 안 내립니다. 프로필 화면 하나 보고 나갈지 말지 정합니다. 프로필 첫 화면에서 보이는 것은 프로필 사진과 소개글과 하이라이트와 최근 게시물 아홉 개입니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=4 AND l.seq=1 AND l.title='학부모는 3초 안에 판단한다';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:33 4줄 공식 · 3:06 이름 짓기', timeline='[{"t":0,"label":"인트로"},{"t":93,"label":"4줄 공식"},{"t":186,"label":"이름 짓기"}]'::jsonb, doc='누구를 위한 학원인지, 뭐가 다른지, 믿을 근거는 무엇인지, 뭘 하면 되는지. 1주차 여섯 문장의 압축판입니다. 여기서도 새로 쓰는 게 아니라 있는 재료를 줄이는 것입니다. 검색되는 이름 짓기도 같이 합니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=4 AND l.seq=2 AND l.title='소개글 4줄 공식';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:23 상담 준비 · 2:46 정리', timeline='[{"t":0,"label":"인트로"},{"t":83,"label":"상담 준비"},{"t":166,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='예약 응대의 톤, 확인 연락, 오시는 길 안내까지. 학부모는 학원에 도착하기 전에 이미 절반을 판단합니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=5 AND l.seq=1 AND l.title='상담은 예약 순간부터 시작된다';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:50 도착 3분 · 3:40 정리', timeline='[{"t":0,"label":"인트로"},{"t":110,"label":"도착 3분"},{"t":220,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='문 앞까지 나가 기다리기, 환영의 인사, 꽃 한 송이, 메뉴판. 이 학원은 우리를 기다렸구나를 만드는 장치들입니다. 비용은 거의 안 들고 효과는 즉시 나타납니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=5 AND l.seq=2 AND l.title='환영받은 기분 — 도착 후 3분의 설계';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:15 클로징 문장 · 2:30 거절 응대', timeline='[{"t":0,"label":"인트로"},{"t":75,"label":"클로징 문장"},{"t":150,"label":"거절 응대"}]'::jsonb, doc='클로징을 화법이 아니라 준비된 한 문장으로 합니다. 어물어물 넘기다 연락드릴게요로 끝나는 상담과, 자연스럽게 등록을 묻는 상담의 차이입니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=5 AND l.seq=3 AND l.title='등록하시겠어요 — CTA는 문구다';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:28 퇴원 징후 · 2:56 정리', timeline='[{"t":0,"label":"인트로"},{"t":88,"label":"퇴원 징후"},{"t":176,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='결석과 지각 패턴의 변화, 숙제 질 저하, 학부모 답장 톤의 변화, 요즘 애가 힘들어해서요라는 말. 퇴원은 갑자기 오지 않습니다. 신호를 놓쳤을 뿐입니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=6 AND l.seq=1 AND l.title='갑자기 그만두는 학생은 없다';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:36 리포트 양식 · 3:13 소개가 나오는 순간', timeline='[{"t":0,"label":"인트로"},{"t":96,"label":"리포트 양식"},{"t":193,"label":"소개가 나오는 순간"}]'::jsonb, doc='신규 한 명 데려오는 비용보다 재원생 한 명 지키는 비용이 훨씬 쌉니다. 구멍 난 독에 물 붓기를 멈추는 것이 먼저입니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=6 AND l.seq=2 AND l.title='학부모 리포트와 소개가 나오는 구조';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:41 채널 성격 · 3:23 정리', timeline='[{"t":0,"label":"인트로"},{"t":101,"label":"채널 성격"},{"t":203,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='유튜브 롱폼, 쓰레드, 맘카페, 당근, 파워링크, 전단지와 현수막. 각각 누가 보는가, 성과까지 걸리는 시간, 원장 시간 소요, 어떤 학원에 맞는가.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=7 AND l.seq=1 AND l.title='채널 6종 성격표';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:25 채널 두 개 고르기 · 2:50 문의 동선', timeline='[{"t":0,"label":"인트로"},{"t":85,"label":"채널 두 개 고르기"},{"t":170,"label":"문의 동선"}]'::jsonb, doc='채널을 늘리는 게 성장이 아닙니다. 어설픈 여섯 개보다 제대로 된 두 개입니다. 어느 문으로 들어와도 플레이스와 블로그를 거쳐 문의는 상담 시스템이 받습니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=7 AND l.seq=2 AND l.title='모든 길은 한 곳으로';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:53 소통 체계 · 3:46 정리', timeline='[{"t":0,"label":"인트로"},{"t":113,"label":"소통 체계"},{"t":226,"label":"정리 · 다음 레슨 예고"}]'::jsonb, doc='출결, 학생 특이사항, 학부모 컴플레인이 생기면 강사는 어디로 어떤 형식으로 보고하는가. 보고 체계를 일원화하고 양식화합니다. 그래서 원장만 모르는 일이 없게 만듭니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=8 AND l.seq=1 AND l.title='정보가 원장을 거치지 않고도 원장에게 닿게';
UPDATE ext_lesson l SET video_url='https://www.youtube.com/watch?v=d3RNpwbWaJU', description='0:00 인트로 · 1:31 원칙 목록 · 3:03 환불 · 보강 규정', timeline='[{"t":0,"label":"인트로"},{"t":91,"label":"원칙 목록"},{"t":183,"label":"환불 · 보강 규정"}]'::jsonb, doc='매뉴얼은 두꺼운 문서가 아니라 우리 학원의 원칙 목록입니다. 결석 대응, 보강 규정, 컴플레인 1차 응대, 환불. 원장이 없어도 같은 결정이 나오게 합니다.' FROM ext_section s, lounge g WHERE s.id=l.section_id AND g.course_id=s.course_id AND g.id=1 AND s.seq=8 AND l.seq=2 AND l.title='학원의 결정은 원장이 아니라 원칙이 한다';
DO $$ DECLARE n int; BEGIN SELECT count(*) INTO n FROM ext_lesson l JOIN ext_section s ON s.id=l.section_id JOIN lounge g ON g.course_id=s.course_id WHERE g.id=1 AND jsonb_array_length(coalesce(l.timeline,'[]'))=0; RAISE NOTICE '타임라인 없는 샘플 레슨 %건 (0 이어야 한다)', n; END $$;
COMMIT;
