-- =============================================================================
-- 프드프 라운지 · 시드
--
-- db/make-seed.js 가 web/assets/data-mock.js 에서 뽑아 만든다. 직접 고치지 말 것.
-- 목업 데이터를 고치고 다시 돌린다:
--
--     node db/make-seed.js > db/seed.sql
--
-- 시각은 전부 불러오는 시점(now()) 기준 상대값이다. 며칠 뒤에 넣어도
-- '어제 올라온 글'과 '이번 주 미제출'이 그대로 말이 된다.
-- =============================================================================

SET TIME ZONE 'UTC';

BEGIN;

TRUNCATE lounge_week, lounge_digest, feedback_pass_use, post_view, reaction, comment,
  attachment, post_answer, post, lounge_category, category, lounge_member,
  lounge RESTART IDENTITY CASCADE;
TRUNCATE ext_live, ext_feedback_pass, ext_watch, ext_purchase, ext_mission,
  ext_lesson, ext_week, ext_course, ext_user RESTART IDENTITY CASCADE;


-- =============================================================================
-- 프드프 캐시 (운영에서는 API 응답으로 채워진다)
-- =============================================================================

-- 계정
INSERT INTO ext_user (id, nickname, email, synced_at) VALUES
  (1, '김선주', 'user1@example.com', now()),
  (2, '정해린', 'user2@example.com', now()),
  (3, '오승민', 'user3@example.com', now()),
  (4, '한지수', 'user4@example.com', now()),
  (5, '최은영', 'user5@example.com', now()),
  (6, '박민경', 'user6@example.com', now()),
  (7, '박현종', 'user7@example.com', now()),
  (8, '윤서진', 'user8@example.com', now()),
  (9, '장미래', 'user9@example.com', now()),
  (10, '임도현', 'user10@example.com', now()),
  (11, '송가은', 'user11@example.com', now()),
  (12, '신우철', 'user12@example.com', now()),
  (13, '강예린', 'user13@example.com', now()),
  (14, '홍수민', 'user14@example.com', now()),
  (15, '배성호', 'user15@example.com', now()),
  (16, '노아름', 'user16@example.com', now()),
  (17, '권태윤', 'user17@example.com', now()),
  (18, '문지호', 'user18@example.com', now()),
  (19, '조은비', 'user19@example.com', now()),
  (20, '서다인', 'user20@example.com', now()),
  (21, '황준서', 'user21@example.com', now()),
  (22, '양소희', 'user22@example.com', now()),
  (23, '구민재', 'user23@example.com', now()),
  (24, '천유나', 'user24@example.com', now()),
  (25, '김경원', 'user25@example.com', now()),
  (26, '프드프 관리자', 'user26@example.com', now());

-- 강의
INSERT INTO ext_course (id, title, weeks, synced_at) VALUES
  (1, '학원마케팅 올인원 강의', 8, now());

-- 주차 제목. 강의 목록의 카드 제목이 된다.
INSERT INTO ext_week (course_id, week, title, synced_at) VALUES
  (1, 1, '옆 학원 말고, 왜 우리 학원인데?', now()),
  (1, 2, '원장님 학원, 검색하면 나와요?', now()),
  (1, 3, '블로그 100개 썼는데, 왜 문의는 0건일까요?', now()),
  (1, 4, '선택이 아닌 필수, 학원 인스타', now()),
  (1, 5, '99% 등록으로 이루어지는 상담의 기술', now()),
  (1, 6, '신규 100명보다 더 중요한 재원생 관리', now()),
  (1, 7, '유튜브 · 맘카페 · 당근 채널 확장 전략', now()),
  (1, 8, '원장 수업 없는 학원 시스템 만들기', now());

-- 주차별 강. 교안 본문이 통합 검색의 대상이 된다.
INSERT INTO ext_lesson (course_id, week, seq, chapter, title, duration, video_url, doc, synced_at) VALUES
  (1, 1, 1, '고객 정의', '우리 학원의 주인공은 누구인가', '5:10', 'https://customer-xxxx.cloudflarestream.com/1-1-1/iframe', '여러분 학원의 주인공은 어떤 아이입니까. 그리고 뒤집어서, 안 받을 학생을 말할 수 있습니까. 학생을 정하면 학부모도 정해집니다. 그 학부모가 밤에 무엇을 검색하고, 상담 전화에서 무엇을 차마 못 묻는지까지 따라옵니다.', now()),
  (1, 1, 2, '경쟁사 분석', '옆 학원은 뭐라고 말하고 있는가', '4:30', 'https://customer-xxxx.cloudflarestream.com/1-1-2/iframe', '우리 동네 학원 다섯 곳의 소개글을 나란히 놓으면 이름을 가려도 구분이 됩니까. 경쟁 분석의 목적은 이기는 게 아니라 빈자리를 찾는 것입니다. 다들 상위권과 소수정예를 외칠 때 아무도 안 서 있는 자리는 어디인가.', now()),
  (1, 1, 3, '포지셔닝', '학원 소개 6문장 쓰기', '6:20', NULL, '타겟 선언, 진짜 문제, 우리의 방법, 증거, 차별점 한 방, 다음 행동 제안. 여섯 문장이 전부 주인공 정의에서 흘러나옵니다. 이 여섯 문장이 이후 블로그와 인스타와 상담 멘트의 기초가 됩니다.', now()),
  (1, 2, 1, '검색 여정', '학부모는 어떤 경로로 학원을 찾는가', '4:15', 'https://customer-xxxx.cloudflarestream.com/1-2-1/iframe', '소개받은 학부모도 등록 전에 반드시 하는 행동이 있습니다. 검색입니다. 검색에서 플레이스 목록, 사진과 리뷰 훑기, 블로그 확인, 그리고 문의. 이 여정의 각 단계마다 학부모가 이탈합니다.', now()),
  (1, 2, 2, '플레이스', '플레이스 전면 재세팅', '4:05', 'https://customer-xxxx.cloudflarestream.com/1-2-2/iframe', '상위노출을 결정하는 요소들. 소개글은 새로 쓰는 게 아니라 1주차 여섯 문장을 축약해서 붙이는 것입니다. 사진은 학부모가 확인하고 싶은 것 순서대로 공간, 수업, 아이들. 리뷰는 요청하는 법과 답글 다는 법.', now()),
  (1, 3, 1, '키워드', '학부모는 블로그에서 무엇을 검색하는가', '4:20', 'https://customer-xxxx.cloudflarestream.com/1-3-1/iframe', '학부모는 학원 소식을 검색하지 않습니다. 1주차 주인공 학부모가 밤에 검색하는 말들이 곧 키워드입니다. 지역 키워드와 고민 키워드 두 갈래로 모읍니다.', now()),
  (1, 3, 2, '블로그 3종 세트', '블로그 3종 세트 — 이것부터 쓰면 된다', '4:55', 'https://customer-xxxx.cloudflarestream.com/1-3-2/iframe', '소개하기는 1주차 여섯 문장을 글 한 편으로 풀어낸 것입니다. 학부모 질문 TOP 10은 상담 전화에서 실제로 받는 질문에 미리 답하기. 고객의 언어는 학부모가 차마 못 묻는 걱정을 먼저 꺼내서 답하기.', now()),
  (1, 3, 3, '콘텐츠 분류', '콘텐츠 5기둥 — 올리는 모든 것의 분류함', '4:05', NULL, '전문가로 실력을 증명하고, 철학으로 왜 이렇게 가르치는지 말하고, 증거로 변화 사례와 후기를 쌓고, 신뢰로 일상과 사람 냄새를 내고, 상품으로 모집과 안내를 합니다. 다섯 중 어디에도 안 들어가면 안 올려도 됩니다.', now()),
  (1, 4, 1, '프로필', '학부모는 3초 안에 판단한다', '3:50', 'https://customer-xxxx.cloudflarestream.com/1-4-1/iframe', '학부모는 피드를 안 내립니다. 프로필 화면 하나 보고 나갈지 말지 정합니다. 프로필 첫 화면에서 보이는 것은 프로필 사진과 소개글과 하이라이트와 최근 게시물 아홉 개입니다.', now()),
  (1, 4, 2, '계정 세팅', '소개글 4줄 공식', '4:40', NULL, '누구를 위한 학원인지, 뭐가 다른지, 믿을 근거는 무엇인지, 뭘 하면 되는지. 1주차 여섯 문장의 압축판입니다. 여기서도 새로 쓰는 게 아니라 있는 재료를 줄이는 것입니다. 검색되는 이름 짓기도 같이 합니다.', now()),
  (1, 5, 1, '상담 준비', '상담은 예약 순간부터 시작된다', '4:10', 'https://customer-xxxx.cloudflarestream.com/1-5-1/iframe', '예약 응대의 톤, 확인 연락, 오시는 길 안내까지. 학부모는 학원에 도착하기 전에 이미 절반을 판단합니다.', now()),
  (1, 5, 2, '도착 3분', '환영받은 기분 — 도착 후 3분의 설계', '5:30', 'https://customer-xxxx.cloudflarestream.com/1-5-2/iframe', '문 앞까지 나가 기다리기, 환영의 인사, 꽃 한 송이, 메뉴판. 이 학원은 우리를 기다렸구나를 만드는 장치들입니다. 비용은 거의 안 들고 효과는 즉시 나타납니다.', now()),
  (1, 5, 3, '클로징', '등록하시겠어요 — CTA는 문구다', '3:45', NULL, '클로징을 화법이 아니라 준비된 한 문장으로 합니다. 어물어물 넘기다 연락드릴게요로 끝나는 상담과, 자연스럽게 등록을 묻는 상담의 차이입니다.', now()),
  (1, 6, 1, '퇴원 징후', '갑자기 그만두는 학생은 없다', '4:25', 'https://customer-xxxx.cloudflarestream.com/1-6-1/iframe', '결석과 지각 패턴의 변화, 숙제 질 저하, 학부모 답장 톤의 변화, 요즘 애가 힘들어해서요라는 말. 퇴원은 갑자기 오지 않습니다. 신호를 놓쳤을 뿐입니다.', now()),
  (1, 6, 2, '소통 체계', '학부모 리포트와 소개가 나오는 구조', '4:50', NULL, '신규 한 명 데려오는 비용보다 재원생 한 명 지키는 비용이 훨씬 쌉니다. 구멍 난 독에 물 붓기를 멈추는 것이 먼저입니다.', now()),
  (1, 7, 1, '채널 성격', '채널 6종 성격표', '5:05', 'https://customer-xxxx.cloudflarestream.com/1-7-1/iframe', '유튜브 롱폼, 쓰레드, 맘카페, 당근, 파워링크, 전단지와 현수막. 각각 누가 보는가, 성과까지 걸리는 시간, 원장 시간 소요, 어떤 학원에 맞는가.', now()),
  (1, 7, 2, '퍼널', '모든 길은 한 곳으로', '4:15', NULL, '채널을 늘리는 게 성장이 아닙니다. 어설픈 여섯 개보다 제대로 된 두 개입니다. 어느 문으로 들어와도 플레이스와 블로그를 거쳐 문의는 상담 시스템이 받습니다.', now()),
  (1, 8, 1, '소통 체계', '정보가 원장을 거치지 않고도 원장에게 닿게', '5:40', 'https://customer-xxxx.cloudflarestream.com/1-8-1/iframe', '출결, 학생 특이사항, 학부모 컴플레인이 생기면 강사는 어디로 어떤 형식으로 보고하는가. 보고 체계를 일원화하고 양식화합니다. 그래서 원장만 모르는 일이 없게 만듭니다.', now()),
  (1, 8, 2, '업무 매뉴얼', '학원의 결정은 원장이 아니라 원칙이 한다', '4:35', NULL, '매뉴얼은 두꺼운 문서가 아니라 우리 학원의 원칙 목록입니다. 결석 대응, 보강 규정, 컴플레인 1차 응대, 환불. 원장이 없어도 같은 결정이 나오게 합니다.', now());

-- 주차별 미션 양식. 글쓰기 창의 과제 폼이 이걸 읽는다.
INSERT INTO ext_mission (course_id, week, title, seq, question, hint, synced_at) VALUES
  (1, 1, '1주차 미션 · 우리 학원의 주인공 정하기', 1, '우리 학원의 주인공은 어떤 아이인가요?', '예: 머리가 나쁜 게 아니라 어느 순간 수학을 포기하는 게 편해진 아이', now()),
  (1, 1, '1주차 미션 · 우리 학원의 주인공 정하기', 2, '반대로, 안 받을 학생을 한 줄로 적어보세요.', '예: 저는 전교 1등을 안 받습니다', now()),
  (1, 1, '1주차 미션 · 우리 학원의 주인공 정하기', 3, '둘을 합쳐 우리 학원을 한 문장으로 쓰면?', '옆 학원이 가져다 써도 말이 되면 아직 우리 문장이 아닙니다', now()),
  (1, 2, '2주차 미션 · 플레이스 다시 세팅하기', 1, '''○○동 수학학원''을 검색하면 우리는 몇 번째에 나오나요?', '예: 1페이지에 없습니다. 2페이지 중간쯤', now()),
  (1, 2, '2주차 미션 · 플레이스 다시 세팅하기', 2, '학부모가 우리를 놓치는 단계는 어디인가요?', '검색 → 플레이스 목록 → 사진·리뷰 → 블로그 → 문의 중에서', now()),
  (1, 2, '2주차 미션 · 플레이스 다시 세팅하기', 3, '1주차 여섯 문장을 줄여 플레이스 소개글을 적어보세요.', '새로 쓰는 게 아니라 있는 걸 줄이는 겁니다', now()),
  (1, 3, '3주차 미션 · 학부모가 검색하는 말로 글 쓰기', 1, '주인공 학부모가 밤에 검색하는 말 세 개를 적으세요.', '지역 키워드(○○동 수학학원) + 고민 키워드(수포자 학원)', now()),
  (1, 3, '3주차 미션 · 학부모가 검색하는 말로 글 쓰기', 2, '학부모가 상담에서 차마 못 묻는 걱정은 무엇인가요?', '예: 우리 애만 못 따라가면 어쩌죠', now()),
  (1, 3, '3주차 미션 · 학부모가 검색하는 말로 글 쓰기', 3, '그 걱정에 먼저 답하는 글의 제목을 지어보세요.', '하고 싶은 말이 아니라 학부모가 검색하는 질문에 답하는 제목', now()),
  (1, 4, '4주차 미션 · 프로필 4줄 다시 쓰기', 1, '지금 우리 계정 프로필 첫 화면에 무엇이 보이나요?', '프사 · 소개글 · 하이라이트 · 최근 게시물 아홉 개', now()),
  (1, 4, '4주차 미션 · 프로필 4줄 다시 쓰기', 2, '소개글 4줄을 적어보세요.', '누구를 위한 / 뭐가 다른 / 믿을 근거 / 뭘 하면 되는지', now()),
  (1, 4, '4주차 미션 · 프로필 4줄 다시 쓰기', 3, '검색되는 계정 이름으로 바꾼다면?', '예: ○○동수학 매쓰플랜', now()),
  (1, 5, '5주차 미션 · 상담 3분 설계하기', 1, '지난달 문의 몇 건 중 몇 건이 등록으로 이어졌나요?', '학생 한 명이 연 120만 원입니다. 숫자로 마주하세요', now()),
  (1, 5, '5주차 미션 · 상담 3분 설계하기', 2, '학부모가 도착한 뒤 3분 동안 무엇을 하시겠습니까?', '예: 문 앞까지 나가 기다리기 · 꽃 한 송이 · 메뉴판', now()),
  (1, 5, '5주차 미션 · 상담 3분 설계하기', 3, '등록을 묻는 한 문장을 미리 적어두세요.', '화법이 아니라 준비된 문장입니다. 어물어물 넘기면 연락드릴게요로 끝납니다', now()),
  (1, 6, '6주차 미션 · 퇴원 신호 찾아내기', 1, '최근 그만둔 학생에게 미리 어떤 신호가 있었나요?', '결석·지각 패턴, 숙제 질, 학부모 답장 톤', now()),
  (1, 6, '6주차 미션 · 퇴원 신호 찾아내기', 2, '지금 그 신호가 보이는 학생은 누구인가요?', '퇴원은 갑자기 오지 않습니다. 놓쳤을 뿐입니다', now()),
  (1, 6, '6주차 미션 · 퇴원 신호 찾아내기', 3, '그 학생에게 이번 주에 무엇을 하시겠습니까?', '예: 개별 면담 10분, 학부모에게 리포트 한 장', now()),
  (1, 7, '7주차 미션 · 채널 두 개만 고르기', 1, '주인공 학부모가 실제로 있는 채널은 어디인가요?', '유튜브 · 쓰레드 · 맘카페 · 당근 · 파워링크 · 전단지 중에서', now()),
  (1, 7, '7주차 미션 · 채널 두 개만 고르기', 2, '내가 지속할 수 있는 채널 두 개를 고르세요.', '어설픈 여섯 개보다 제대로 된 두 개', now()),
  (1, 7, '7주차 미션 · 채널 두 개만 고르기', 3, '버리기로 한 채널과 그 이유는?', '버린 이유가 핵심입니다', now()),
  (1, 8, '8주차 미션 · 원장 없이도 도는 원칙 만들기', 1, '오늘 하루 원장님을 거쳐 간 결정을 세 개 적어보세요.', '출결 확인, 학부모 답장, 강사 질문, 교재 주문', now()),
  (1, 8, '8주차 미션 · 원장 없이도 도는 원칙 만들기', 2, '그중 다른 사람이 결정해도 되는 것은 무엇인가요?', '1차 판단은 중간 관리자가, 원장에게는 걸러진 것만', now()),
  (1, 8, '8주차 미션 · 원장 없이도 도는 원칙 만들기', 3, '우리 학원 원칙 세 개를 적어보세요.', '결석 대응 · 보강 규정 · 컴플레인 1차 응대 · 환불 중에서', now());

-- 구매. 기수와 만료일이 여기서 나온다.
INSERT INTO ext_purchase (user_id, course_id, cohort, purchased_at, expires_at, synced_at) VALUES
  (1, 1, 3, now() - interval '19 days', now() - interval '19 days' + interval '365 days', now()),
  (2, 1, 3, now() - interval '19 days', now() - interval '19 days' + interval '365 days', now()),
  (3, 1, 2, now() - interval '33 days', now() - interval '33 days' + interval '365 days', now()),
  (4, 1, 3, now() - interval '18 days', now() - interval '18 days' + interval '365 days', now()),
  (5, 1, 2, now() - interval '28 days', now() - interval '28 days' + interval '365 days', now()),
  (6, 1, 3, now() - interval '13 days', now() - interval '13 days' + interval '365 days', now()),
  (7, 1, 3, now() - interval '19 days', now() - interval '19 days' + interval '365 days', now()),
  (8, 1, 3, now() - interval '18 days', now() - interval '18 days' + interval '365 days', now()),
  (9, 1, 3, now() - interval '12 days', now() - interval '12 days' + interval '365 days', now()),
  (10, 1, 2, now() - interval '34 days', now() - interval '34 days' + interval '365 days', now()),
  (11, 1, 3, now() - interval '11 days', now() - interval '11 days' + interval '365 days', now()),
  (12, 1, 2, now() - interval '27 days', now() - interval '27 days' + interval '365 days', now()),
  (13, 1, 3, now() - interval '18 days', now() - interval '18 days' + interval '365 days', now()),
  (14, 1, 3, now() - interval '13 days', now() - interval '13 days' + interval '365 days', now()),
  (15, 1, 2, now() - interval '40 days', now() - interval '40 days' + interval '365 days', now()),
  (16, 1, 3, now() - interval '19 days', now() - interval '19 days' + interval '365 days', now()),
  (17, 1, 3, now() - interval '14 days', now() - interval '14 days' + interval '365 days', now()),
  (18, 1, 2, now() - interval '29 days', now() - interval '29 days' + interval '365 days', now()),
  (19, 1, 3, now() - interval '15 days', now() - interval '15 days' + interval '365 days', now()),
  (20, 1, 3, now() - interval '18 days', now() - interval '18 days' + interval '365 days', now()),
  (21, 1, 2, now() - interval '33 days', now() - interval '33 days' + interval '365 days', now()),
  (22, 1, 3, now() - interval '12 days', now() - interval '12 days' + interval '365 days', now()),
  (23, 1, 3, now() - interval '1 days', now() - interval '1 days' + interval '365 days', now()),
  (24, 1, 3, now() - interval '1 days', now() - interval '1 days' + interval '365 days', now());

-- 시청 기록. lounge_member.week 는 이 표에서 계산한 값의 캐시다.
-- 여기서는 '지난 주차의 강은 다 봤다'로 깔아 둔다.
INSERT INTO ext_watch (user_id, lesson_id, watched_at, is_complete, synced_at) VALUES
  (1, 1, now() - interval '16 days', true, now()),
  (1, 2, now() - interval '16 days', true, now()),
  (1, 3, now() - interval '16 days', true, now()),
  (1, 4, now() - interval '13 days', true, now()),
  (1, 5, now() - interval '13 days', true, now()),
  (2, 1, now() - interval '16 days', true, now()),
  (2, 2, now() - interval '16 days', true, now()),
  (2, 3, now() - interval '16 days', true, now()),
  (2, 4, now() - interval '13 days', true, now()),
  (2, 5, now() - interval '13 days', true, now()),
  (3, 1, now() - interval '30 days', true, now()),
  (3, 2, now() - interval '30 days', true, now()),
  (3, 3, now() - interval '30 days', true, now()),
  (3, 4, now() - interval '27 days', true, now()),
  (3, 5, now() - interval '27 days', true, now()),
  (3, 6, now() - interval '24 days', true, now()),
  (3, 7, now() - interval '24 days', true, now()),
  (3, 8, now() - interval '24 days', true, now()),
  (3, 9, now() - interval '21 days', true, now()),
  (3, 10, now() - interval '21 days', true, now()),
  (4, 1, now() - interval '15 days', true, now()),
  (4, 2, now() - interval '15 days', true, now()),
  (4, 3, now() - interval '15 days', true, now()),
  (4, 4, now() - interval '12 days', true, now()),
  (4, 5, now() - interval '12 days', true, now()),
  (5, 1, now() - interval '25 days', true, now()),
  (5, 2, now() - interval '25 days', true, now()),
  (5, 3, now() - interval '25 days', true, now()),
  (5, 4, now() - interval '22 days', true, now()),
  (5, 5, now() - interval '22 days', true, now()),
  (5, 6, now() - interval '19 days', true, now()),
  (5, 7, now() - interval '19 days', true, now()),
  (5, 8, now() - interval '19 days', true, now()),
  (6, 1, now() - interval '10 days', true, now()),
  (6, 2, now() - interval '10 days', true, now()),
  (6, 3, now() - interval '10 days', true, now()),
  (7, 1, now() - interval '16 days', true, now()),
  (7, 2, now() - interval '16 days', true, now()),
  (7, 3, now() - interval '16 days', true, now()),
  (7, 4, now() - interval '13 days', true, now()),
  (7, 5, now() - interval '13 days', true, now()),
  (8, 1, now() - interval '15 days', true, now()),
  (8, 2, now() - interval '15 days', true, now()),
  (8, 3, now() - interval '15 days', true, now()),
  (8, 4, now() - interval '12 days', true, now()),
  (8, 5, now() - interval '12 days', true, now()),
  (9, 1, now() - interval '9 days', true, now()),
  (9, 2, now() - interval '9 days', true, now()),
  (9, 3, now() - interval '9 days', true, now()),
  (10, 1, now() - interval '31 days', true, now()),
  (10, 2, now() - interval '31 days', true, now()),
  (10, 3, now() - interval '31 days', true, now()),
  (10, 4, now() - interval '28 days', true, now()),
  (10, 5, now() - interval '28 days', true, now()),
  (10, 6, now() - interval '25 days', true, now()),
  (10, 7, now() - interval '25 days', true, now()),
  (10, 8, now() - interval '25 days', true, now()),
  (10, 9, now() - interval '22 days', true, now()),
  (10, 10, now() - interval '22 days', true, now()),
  (12, 1, now() - interval '24 days', true, now()),
  (12, 2, now() - interval '24 days', true, now()),
  (12, 3, now() - interval '24 days', true, now()),
  (12, 4, now() - interval '21 days', true, now()),
  (12, 5, now() - interval '21 days', true, now()),
  (12, 6, now() - interval '18 days', true, now()),
  (12, 7, now() - interval '18 days', true, now()),
  (12, 8, now() - interval '18 days', true, now()),
  (13, 1, now() - interval '15 days', true, now()),
  (13, 2, now() - interval '15 days', true, now()),
  (13, 3, now() - interval '15 days', true, now()),
  (13, 4, now() - interval '12 days', true, now()),
  (13, 5, now() - interval '12 days', true, now()),
  (14, 1, now() - interval '10 days', true, now()),
  (14, 2, now() - interval '10 days', true, now()),
  (14, 3, now() - interval '10 days', true, now()),
  (15, 1, now() - interval '37 days', true, now()),
  (15, 2, now() - interval '37 days', true, now()),
  (15, 3, now() - interval '37 days', true, now()),
  (15, 4, now() - interval '34 days', true, now()),
  (15, 5, now() - interval '34 days', true, now()),
  (15, 6, now() - interval '31 days', true, now()),
  (15, 7, now() - interval '31 days', true, now()),
  (15, 8, now() - interval '31 days', true, now()),
  (15, 9, now() - interval '28 days', true, now()),
  (15, 10, now() - interval '28 days', true, now()),
  (15, 11, now() - interval '25 days', true, now()),
  (15, 12, now() - interval '25 days', true, now()),
  (15, 13, now() - interval '25 days', true, now()),
  (16, 1, now() - interval '16 days', true, now()),
  (16, 2, now() - interval '16 days', true, now()),
  (16, 3, now() - interval '16 days', true, now()),
  (16, 4, now() - interval '13 days', true, now()),
  (16, 5, now() - interval '13 days', true, now()),
  (17, 1, now() - interval '11 days', true, now()),
  (17, 2, now() - interval '11 days', true, now()),
  (17, 3, now() - interval '11 days', true, now()),
  (18, 1, now() - interval '26 days', true, now()),
  (18, 2, now() - interval '26 days', true, now()),
  (18, 3, now() - interval '26 days', true, now()),
  (18, 4, now() - interval '23 days', true, now()),
  (18, 5, now() - interval '23 days', true, now()),
  (18, 6, now() - interval '20 days', true, now()),
  (18, 7, now() - interval '20 days', true, now()),
  (18, 8, now() - interval '20 days', true, now()),
  (20, 1, now() - interval '15 days', true, now()),
  (20, 2, now() - interval '15 days', true, now()),
  (20, 3, now() - interval '15 days', true, now()),
  (20, 4, now() - interval '12 days', true, now()),
  (20, 5, now() - interval '12 days', true, now()),
  (21, 1, now() - interval '30 days', true, now()),
  (21, 2, now() - interval '30 days', true, now()),
  (21, 3, now() - interval '30 days', true, now()),
  (21, 4, now() - interval '27 days', true, now()),
  (21, 5, now() - interval '27 days', true, now()),
  (21, 6, now() - interval '24 days', true, now()),
  (21, 7, now() - interval '24 days', true, now()),
  (21, 8, now() - interval '24 days', true, now()),
  (21, 9, now() - interval '21 days', true, now()),
  (21, 10, now() - interval '21 days', true, now()),
  (22, 1, now() - interval '9 days', true, now()),
  (22, 2, now() - interval '9 days', true, now()),
  (22, 3, now() - interval '9 days', true, now());

-- 피드백권 잔여. 소유는 프드프 소관이고 라운지는 읽기만 한다.
INSERT INTO ext_feedback_pass (user_id, course_id, quota_per, period, period_start, used, synced_at) VALUES
  (1, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (2, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (3, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (4, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (5, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (6, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (7, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (8, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (9, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (10, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (11, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (12, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (13, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (14, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (15, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (16, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (17, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (18, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (19, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (20, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (21, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (22, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (23, 1, 3, 'week', date_trunc('week', now())::date, 0, now()),
  (24, 1, 3, 'week', date_trunc('week', now())::date, 0, now());

-- 다음 라이브
INSERT INTO ext_live (course_id, title, starts_at, synced_at) VALUES
  (1, '4주차 라이브 · 인스타 프로필 첨삭', now() + interval '2 days', now());

-- =============================================================================
-- 라운지
-- =============================================================================

-- 강의 하나에 라운지 하나. 나머지 둘은 필터 관리에서 '다른 라운지가 사용 중'을
-- 보여주기 위해 같이 둔다.
INSERT INTO lounge (id, course_id, name, intro) OVERRIDING SYSTEM VALUE VALUES
  (1, 1, '학원마케팅 올인원 강의', '강의를 듣기 전에 여기 먼저 들르는 곳입니다. 과제도, 피드백도, 등록 인증도 이 안에서 끝납니다. 잘 쓴 글보다 자주 들르는 게 중요합니다.'),
  (2, 2, '학원마케팅 올인원 강의 (샘플)', NULL);

-- 주차 게시 여부. 강의 내용은 프드프 것이고 여는 시점은 라운지 것이다.
INSERT INTO lounge_week (lounge_id, week, published) VALUES
  (1, 1, true),
  (1, 2, true),
  (1, 3, true),
  (1, 4, true),
  (1, 5, true),
  (1, 6, true),
  (1, 7, true),
  (1, 8, true);

-- 멤버. 역할이 라운지 단위로 붙는다.
INSERT INTO lounge_member (lounge_id, user_id, role, cohort, joined_at, expires_at, last_seen_at, week, week_synced_at) VALUES
  (1, 1, 'student', 3, now() - interval '19 days', now() - interval '19 days' + interval '365 days', now(), 3, now()),
  (1, 2, 'student', 3, now() - interval '19 days', now() - interval '19 days' + interval '365 days', now(), 3, now()),
  (1, 3, 'student', 2, now() - interval '33 days', now() - interval '33 days' + interval '365 days', now() - interval '1 days', 5, now()),
  (1, 4, 'student', 3, now() - interval '18 days', now() - interval '18 days' + interval '365 days', now(), 3, now()),
  (1, 5, 'student', 2, now() - interval '28 days', now() - interval '28 days' + interval '365 days', now() - interval '2 days', 4, now()),
  (1, 6, 'student', 3, now() - interval '13 days', now() - interval '13 days' + interval '365 days', now() - interval '1 days', 2, now()),
  (1, 7, 'student', 3, now() - interval '19 days', now() - interval '19 days' + interval '365 days', now(), 3, now()),
  (1, 8, 'student', 3, now() - interval '18 days', now() - interval '18 days' + interval '365 days', now() - interval '1 days', 3, now()),
  (1, 9, 'student', 3, now() - interval '12 days', now() - interval '12 days' + interval '365 days', now() - interval '3 days', 2, now()),
  (1, 10, 'student', 2, now() - interval '34 days', now() - interval '34 days' + interval '365 days', now() - interval '2 days', 5, now()),
  (1, 11, 'student', 3, now() - interval '11 days', now() - interval '11 days' + interval '365 days', now() - interval '9 days', 1, now()),
  (1, 12, 'student', 2, now() - interval '27 days', now() - interval '27 days' + interval '365 days', now() - interval '1 days', 4, now()),
  (1, 13, 'student', 3, now() - interval '18 days', now() - interval '18 days' + interval '365 days', now(), 3, now()),
  (1, 14, 'student', 3, now() - interval '13 days', now() - interval '13 days' + interval '365 days', now() - interval '4 days', 2, now()),
  (1, 15, 'student', 2, now() - interval '40 days', now() - interval '40 days' + interval '365 days', now() - interval '1 days', 6, now()),
  (1, 16, 'student', 3, now() - interval '19 days', now() - interval '19 days' + interval '365 days', now() - interval '2 days', 3, now()),
  (1, 17, 'student', 3, now() - interval '14 days', now() - interval '14 days' + interval '365 days', now() - interval '11 days', 2, now()),
  (1, 18, 'student', 2, now() - interval '29 days', now() - interval '29 days' + interval '365 days', now() - interval '3 days', 4, now()),
  (1, 19, 'student', 3, now() - interval '15 days', now() - interval '15 days' + interval '365 days', now() - interval '14 days', 1, now()),
  (1, 20, 'student', 3, now() - interval '18 days', now() - interval '18 days' + interval '365 days', now() - interval '1 days', 3, now()),
  (1, 21, 'student', 2, now() - interval '33 days', now() - interval '33 days' + interval '365 days', now(), 5, now()),
  (1, 22, 'student', 3, now() - interval '12 days', now() - interval '12 days' + interval '365 days', now() - interval '8 days', 2, now()),
  (1, 23, 'student', 3, now() - interval '1 days', now() - interval '1 days' + interval '365 days', now(), 1, now()),
  (1, 24, 'student', 3, now() - interval '1 days', now() - interval '1 days' + interval '365 days', now(), 1, now()),
  (1, 25, 'instructor', NULL, now() - interval '120 days', NULL, now(), 8, now()),
  (1, 26, 'admin', NULL, now() - interval '400 days', NULL, now(), 8, now());
INSERT INTO lounge_member (lounge_id, user_id, role, joined_at, last_seen_at, week) VALUES
  (2, 26, 'admin', now() - interval '400 days', now(), 1);

-- 카테고리. 전역 풀이다.
INSERT INTO category (id, name, is_system, pass_required) OVERRIDING SYSTEM VALUE VALUES
  (1, '과제', true, false),
  (2, '콘텐츠 피드백', true, true),
  (3, '문구 아이디어', false, false),
  (4, '등록 인증', false, false),
  (5, '자유', false, false),
  (6, '공지', false, false),
  (7, '챌린지', false, false);

-- 라운지별 배치와 쓰기 권한. 행이 없으면 그 라운지에서 '미사용'이다.
INSERT INTO lounge_category (lounge_id, category_id, placement, sort, student_can_write, instructor_can_write) VALUES
  (1, 1, 'show', 0, true, true),
  (1, 2, 'show', 1, true, true),
  (1, 4, 'show', 2, true, true),
  (1, 3, 'more', 0, true, true),
  (1, 5, 'more', 1, true, true),
  (1, 6, 'more', 2, false, true),
  (2, 1, 'show', 0, true, true),
  (2, 2, 'show', 1, true, true),
  (2, 4, 'show', 2, true, true),
  (2, 3, 'more', 0, true, true),
  (2, 5, 'more', 1, true, true),
  (2, 6, 'more', 2, false, true);

-- 글. 글쓴이는 user_id 로 판정하고 author_name 으로 표시한다.
INSERT INTO post (id, lounge_id, category_id, user_id, author_name, title, body, week, is_pinned, reaction_count, comment_count, view_count, created_at, updated_at) OVERRIDING SYSTEM VALUE VALUES
  (1, 1, 6, 26, '프드프 관리자', '이번 달 명예의 전당에 오른 결과물', '강사님이 고른 결과물을 이 글 하나에 계속 쌓습니다. 별도 메뉴 없이 최상단 고정.', NULL, true, 48, 0, 1204, now() - interval '30 days', now() - interval '30 days'),
  (2, 1, 1, 1, '김선주', '3주차 과제 올립니다. 학부모가 검색하는 말로 제목을 바꿔봤어요', NULL, 3, false, 11, 7, 61, now() - interval '2 hours', now() - interval '2 hours'),
  (3, 1, 2, 2, '정해린', '블로그 글 제목이 아직 밋밋한 것 같은데 봐주세요', '고민 키워드를 넣긴 했는데 학부모가 클릭할 만한 제목인지 모르겠습니다.', 3, false, 3, 2, 44, now() - interval '4 hours', now() - interval '4 hours'),
  (4, 1, 1, 7, '박현종', '3주차 과제 늦었지만 올립니다', NULL, 3, false, 5, 0, 38, now() - interval '6 hours', now() - interval '6 hours'),
  (5, 1, 6, 26, '프드프 관리자', '4주차는 수요일 10시에 열립니다', '이번 주차부터 교안이 강의 아래에 같이 올라갑니다. 검색으로 바로 찾을 수 있습니다.', NULL, false, 14, 0, 210, now() - interval '1 days', now() - interval '1 days'),
  (6, 1, 4, 3, '오승민', '플레이스만 고쳤는데 이번 주 문의가 4건 들어왔습니다', '사진 순서를 공간·수업·아이들로 바꾸고 소개글을 1주차 여섯 문장에서 줄여 붙였습니다. 그게 전부입니다.', 2, false, 32, 2, 187, now() - interval '1 days', now() - interval '1 days'),
  (7, 1, 3, 4, '한지수', '안 받을 학생을 적으니 소개글이 확 달라졌어요', '전교 1등을 안 받는다고 쓰는 게 무섭더니, 그 한 줄 덕에 나머지 다섯 문장이 저절로 나왔습니다.', NULL, false, 18, 0, 156, now() - interval '2 days', now() - interval '2 days'),
  (8, 1, 1, 7, '박현종', '2주차 과제, 플레이스 소개글 줄여봤습니다', NULL, 2, false, 7, 0, 55, now() - interval '3 days', now() - interval '3 days'),
  (9, 1, 2, 13, '강예린', '제목은 고쳤는데 첫 문단이 아직 학원 소개입니다', '고민 키워드로 제목은 바꿨는데 본문 시작을 어떻게 열어야 할지 모르겠습니다. 봐주세요.', 3, false, 1, 0, 19, now() - interval '1 days', now() - interval '1 days'),
  (10, 1, 2, 10, '임도현', '인스타 소개 두 줄인데 뭘 빼야 할지 모르겠습니다', '수업 과목이랑 지역이랑 경력을 다 넣었더니 읽히지가 않습니다.', 5, false, 2, 0, 27, now() - interval '2 days', now() - interval '2 days'),
  (11, 1, 1, 4, '한지수', '3주차 과제, 학부모가 밤에 검색하는 말 찾아봤습니다', NULL, 3, false, 6, 1, 43, now() - interval '1 days', now() - interval '1 days'),
  (12, 1, 1, 13, '강예린', '3주차 과제 올립니다', '고민 키워드를 찾는 게 지역 키워드보다 훨씬 어려웠습니다. 상담 메모를 다시 뒤져서 세 개 뽑았어요.', 3, false, 4, 0, 31, now() - interval '1 days', now() - interval '1 days'),
  (13, 1, 1, 3, '오승민', '5주차 과제, 인스타 프로필 고쳐봤습니다', '소개 첫 줄을 학원 이름에서 ''초등 영어가 늦었다고 생각하는 학부모님께''로 바꿨습니다. 팔로워보다 저장이 먼저 늘더라고요.', 5, false, 11, 1, 68, now() - interval '2 days', now() - interval '2 days'),
  (14, 1, 1, 12, '신우철', '4주차 과제, 블로그 3종 세트 중 하나 써봤습니다', '고민 해결형으로 하나 썼는데 쓰다 보니 결국 학원 자랑이 됐습니다. 다시 씁니다.', 4, false, 3, 0, 29, now() - interval '2 days', now() - interval '2 days'),
  (15, 1, 1, 8, '윤서진', '3주차 과제 — 논술학원은 고민 키워드가 뭘까 고민했습니다', '수학이나 영어처럼 점수가 안 보이는 과목이라 학부모 걱정도 막연하더라고요. ''글을 못 쓴다''가 아니라 ''생각을 정리 못 한다''였습니다.', 3, false, 5, 1, 37, now() - interval '3 days', now() - interval '3 days'),
  (16, 1, 1, 15, '배성호', '6주차 과제, 후기 요청 문구 만들었습니다', '성적이 오른 학생만 찾다가 아무한테도 못 물었습니다. 그냥 다닌 지 6개월 넘은 분들께 보냈더니 세 분이 써주셨어요.', 6, false, 9, 0, 58, now() - interval '4 days', now() - interval '4 days'),
  (17, 1, 1, 5, '최은영', '4주차 과제 늦게 올립니다', '블로그 제목 열 개를 뽑아봤는데 여덟 개가 학원 소식이었습니다. 두 개만 남기고 다시 뽑겠습니다.', 4, false, 2, 0, 24, now() - interval '4 days', now() - interval '4 days'),
  (18, 1, 1, 21, '황준서', '5주차 과제, 릴스 첫 3초 다시 찍었습니다', '학원 간판부터 보여주던 걸 아이가 문제 푸는 손으로 바꿨습니다. 끝까지 본 비율이 두 배가 됐어요.', 5, false, 7, 1, 45, now() - interval '5 days', now() - interval '5 days'),
  (19, 1, 1, 20, '서다인', '2주차 과제, 플레이스 사진부터 다 갈았습니다', '교실 사진이 한 장도 없었습니다. 수업 중 사진은 동의를 받아야 해서 빈 교실이랑 칠판 위주로 찍었어요.', 2, false, 3, 0, 26, now() - interval '5 days', now() - interval '5 days'),
  (20, 1, 1, 14, '홍수민', '2주차 과제 올립니다. 검색 순위 확인해봤어요', '''상계동 국어학원''으로 검색하니 2페이지에도 없었습니다. 플레이스 등록 자체가 안 돼 있었네요.', 2, false, 4, 0, 33, now() - interval '6 days', now() - interval '6 days'),
  (21, 1, 2, 5, '최은영', '소개 여섯 문장 중 네 번째가 약한 것 같습니다', '증거 문장인데 숫자만 나열한 느낌이라 믿음이 안 갈까 걱정입니다.', 1, false, 2, 0, 40, now() - interval '5 days', now() - interval '5 days'),
  (22, 1, 5, 6, '박민경', '1주차 마치고 남기는 짧은 후기', '주인공을 정하라는 말이 제일 어려웠습니다. 정하고 나니 그다음이 다 쉬워졌어요.', NULL, false, 8, 0, 77, now() - interval '6 days', now() - interval '6 days'),
  (23, 1, 3, 1, '김선주', '상담에서 들은 학부모 말을 그대로 적어두고 있습니다', '제가 만든 문장보다 학부모가 한 말이 훨씬 잘 걸립니다. 녹음 대신 상담 끝나고 바로 메모합니다.', 1, false, 16, 0, 134, now() - interval '7 days', now() - interval '7 days');

-- 과제 미션 답변. 질문 문구도 그때 것으로 같이 남긴다.
INSERT INTO post_answer (post_id, seq, question, answer) VALUES
  (2, 1, '주인공 학부모가 밤에 검색하는 말 세 개를 적으세요.', '중계동 수학학원 / 수포자 학원 / 중2 수학 포기'),
  (2, 2, '학부모가 상담에서 차마 못 묻는 걱정은 무엇인가요?', '우리 애만 진도를 못 따라가서 창피당하면 어쩌나. 이걸 대놓고 물어본 학부모는 12년 동안 한 분도 없었습니다.'),
  (2, 3, '그 걱정에 먼저 답하는 글의 제목을 지어보세요.', '"우리 애만 못 따라가면 어쩌죠" — 중계동 학부모님이 가장 많이 하신 질문'),
  (4, 1, '주인공 학부모가 밤에 검색하는 말 세 개를 적으세요.', '상계동 영어학원 / 초등 영어 늦었나 / 파닉스 다시'),
  (4, 2, '학부모가 상담에서 차마 못 묻는 걱정은 무엇인가요?', '지금 시작하면 너무 늦은 거 아닌가요. 이 말을 꺼내기 미안해하시더라고요.'),
  (4, 3, '그 걱정에 먼저 답하는 글의 제목을 지어보세요.', '초등 4학년에 파닉스 다시 시작해도 되나요 — 늦었다고 생각하는 학부모님께'),
  (8, 1, '''○○동 수학학원''을 검색하면 우리는 몇 번째에 나오나요?', '1페이지에 아예 없었습니다. 2페이지 중간에 있더라고요.'),
  (8, 2, '학부모가 우리를 놓치는 단계는 어디인가요?', '플레이스 목록까지는 오는데 사진에서 나가는 것 같습니다. 교실 사진이 한 장도 없었어요.'),
  (8, 3, '1주차 여섯 문장을 줄여 플레이스 소개글을 적어보세요.', '영어가 늦었다고 생각하는 초등 고학년이 주인공인 학원입니다. 파닉스부터 다시 잡습니다.'),
  (11, 1, '주인공 학부모가 밤에 검색하는 말 세 개를 적으세요.', '창동 수학학원 / 초6 수학 선행 / 중학교 가기 전 수학'),
  (11, 2, '학부모가 상담에서 차마 못 묻는 걱정은 무엇인가요?', '선행을 안 시키면 중학교 가서 뒤처지는 거 아닌지. 다들 시킨다는데 우리만 안 하는 것 같다고 하십니다.'),
  (11, 3, '그 걱정에 먼저 답하는 글의 제목을 지어보세요.', '선행을 안 시켜도 되나요 — 중학교 가기 전 수학, 창동 학부모님께');

-- 첨부
INSERT INTO attachment (post_id, kind, url, label, sort) VALUES
  (2, 'image', '', '블로그 글 캡처 · 중계동 학부모님이 가장 많이 하신 질문', 0),
  (3, 'link', 'https://blog.naver.com/mathplan/223405118826', '중계동 수학학원 — 우리 아이가 수학을 포기한 진짜 이유', 0),
  (6, 'youtube', 'https://www.youtube.com/watch?v=d3RNpwbWaJU', '플레이스 세팅 전후 비교 화면', 0),
  (9, 'link', 'https://blog.naver.com/mathmia/223481920374', '미아 수학학원 — 중2 수학, 지금 포기하면 늦나요', 0),
  (10, 'image', '', '인스타 프로필 화면 캡처', 0);

-- 댓글. 답글은 한 단계까지만.
INSERT INTO comment (id, post_id, parent_id, user_id, author_name, body, reaction_count, created_at) OVERRIDING SYSTEM VALUE VALUES
  (1, 2, NULL, 2, '정해린', '제목만 바꿨는데 조회수가 달라지나요? 저는 학원 소식만 올리고 있었네요.', 3, now() - interval '1 hours'),
  (2, 2, 1, 1, '김선주', '소식은 아무도 검색을 안 하더라고요. 학부모가 실제로 치는 말로 바꾸니 유입이 붙었습니다.', 4, now() - interval '50 minutes'),
  (3, 2, 1, 3, '오승민', '저도 같은 실수였습니다. 공지 글만 100개였어요.', 2, now() - interval '40 minutes'),
  (4, 2, 1, 4, '한지수', '고민 키워드가 진짜 세더라고요. 수포자로 하나 썼더니 바로 문의 왔습니다.', 5, now() - interval '35 minutes'),
  (5, 2, 1, 5, '최은영', '저희도 이번 주에 바꿔보려고요.', 1, now() - interval '20 minutes'),
  (6, 2, NULL, 6, '박민경', '세 번째 문장이 제일 좋네요. 그대로 따라 쓰고 싶습니다.', 0, now() - interval '30 minutes'),
  (7, 2, NULL, 25, '김경원', '세 번째 제목, 학부모가 실제로 쓴 말을 그대로 가져온 게 좋습니다. 다만 지역명이 빠졌어요. 중계동을 앞에 붙이면 검색으로도 잡힙니다.', 7, now() - interval '1 days'),
  (8, 3, NULL, 1, '김선주', '진짜 이유 대신 학부모가 쓰는 말을 그대로 넣어보세요. 상담에서 들은 문장이 제일 잘 먹힙니다.', 5, now() - interval '3 hours'),
  (9, 3, NULL, 25, '김경원', '제목은 이 정도면 됩니다. 그보다 첫 문단이 학원 소개로 시작해요. 학부모 걱정 한 줄로 바꿔보세요.', 4, now() - interval '1 days'),
  (10, 6, NULL, 4, '한지수', '축하드려요. 사진 순서만 바꿔도 그렇게 달라지나요?', 4, now() - interval '1 days'),
  (11, 6, NULL, 5, '최은영', '저도 오늘 바로 해보겠습니다', 2, now() - interval '1 days'),
  (12, 11, NULL, 25, '김경원', '두 번째 답이 좋습니다. ''다들 시킨다는데''가 핵심이에요. 제목에도 그 말을 넣어보세요.', 5, now() - interval '1 days'),
  (13, 13, NULL, 10, '임도현', '저장이 늘었다는 게 더 좋은 신호 같은데요. 저도 바꿔보겠습니다.', 3, now() - interval '2 days'),
  (14, 15, NULL, 1, '김선주', '이 구분이 진짜 좋은데요. 저희도 응용할 수 있을 것 같습니다.', 6, now() - interval '3 days'),
  (15, 18, NULL, 3, '오승민', '손 클로즈업 좋네요. 얼굴 안 나와도 되니 부담도 적고요.', 4, now() - interval '4 days');

-- 반응
INSERT INTO reaction (target_kind, target_id, user_id, emoji, created_at) VALUES
  ('post', 1, 1, '👍', now() - interval '30 days'),
  ('post', 1, 2, '👍', now() - interval '30 days'),
  ('post', 1, 3, '👍', now() - interval '30 days'),
  ('post', 1, 4, '👍', now() - interval '30 days'),
  ('post', 1, 5, '👍', now() - interval '30 days'),
  ('post', 1, 6, '👍', now() - interval '30 days'),
  ('post', 1, 7, '👍', now() - interval '30 days'),
  ('post', 1, 8, '👍', now() - interval '30 days'),
  ('post', 1, 9, '👍', now() - interval '30 days'),
  ('post', 1, 10, '👍', now() - interval '30 days'),
  ('post', 1, 11, '👍', now() - interval '30 days'),
  ('post', 1, 12, '👍', now() - interval '30 days'),
  ('post', 1, 13, '👍', now() - interval '30 days'),
  ('post', 1, 14, '👍', now() - interval '30 days'),
  ('post', 1, 15, '👍', now() - interval '30 days'),
  ('post', 1, 16, '👍', now() - interval '30 days'),
  ('post', 1, 17, '👍', now() - interval '30 days'),
  ('post', 1, 18, '👍', now() - interval '30 days'),
  ('post', 1, 19, '👍', now() - interval '30 days'),
  ('post', 1, 20, '👍', now() - interval '30 days'),
  ('post', 1, 21, '👍', now() - interval '30 days'),
  ('post', 1, 22, '👍', now() - interval '30 days'),
  ('post', 1, 23, '👍', now() - interval '30 days'),
  ('post', 1, 24, '👍', now() - interval '30 days'),
  ('post', 1, 25, '👍', now() - interval '30 days'),
  ('post', 2, 2, '👍', now() - interval '2 hours'),
  ('post', 2, 3, '👍', now() - interval '2 hours'),
  ('post', 2, 4, '👍', now() - interval '2 hours'),
  ('post', 2, 5, '👍', now() - interval '2 hours'),
  ('post', 2, 6, '👍', now() - interval '2 hours'),
  ('post', 2, 7, '👍', now() - interval '2 hours'),
  ('post', 2, 8, '👍', now() - interval '2 hours'),
  ('post', 2, 9, '👍', now() - interval '2 hours'),
  ('post', 2, 10, '👍', now() - interval '2 hours'),
  ('post', 2, 11, '🔥', now() - interval '2 hours'),
  ('post', 2, 12, '🔥', now() - interval '2 hours'),
  ('comment', 1, 1, '👍', now() - interval '1 hours'),
  ('comment', 1, 3, '👍', now() - interval '1 hours'),
  ('comment', 1, 4, '👍', now() - interval '1 hours'),
  ('comment', 2, 2, '👍', now() - interval '50 minutes'),
  ('comment', 2, 3, '👍', now() - interval '50 minutes'),
  ('comment', 2, 4, '👍', now() - interval '50 minutes'),
  ('comment', 2, 5, '👍', now() - interval '50 minutes'),
  ('comment', 3, 1, '👍', now() - interval '40 minutes'),
  ('comment', 3, 2, '👍', now() - interval '40 minutes'),
  ('comment', 4, 1, '👍', now() - interval '35 minutes'),
  ('comment', 4, 2, '👍', now() - interval '35 minutes'),
  ('comment', 4, 3, '👍', now() - interval '35 minutes'),
  ('comment', 4, 5, '👍', now() - interval '35 minutes'),
  ('comment', 4, 6, '👍', now() - interval '35 minutes'),
  ('comment', 5, 1, '👍', now() - interval '20 minutes'),
  ('comment', 7, 1, '👍', now() - interval '1 days'),
  ('comment', 7, 2, '👍', now() - interval '1 days'),
  ('comment', 7, 3, '👍', now() - interval '1 days'),
  ('comment', 7, 4, '👍', now() - interval '1 days'),
  ('comment', 7, 5, '👍', now() - interval '1 days'),
  ('comment', 7, 6, '👍', now() - interval '1 days'),
  ('comment', 7, 7, '👍', now() - interval '1 days'),
  ('post', 3, 1, '👍', now() - interval '4 hours'),
  ('post', 3, 3, '👍', now() - interval '4 hours'),
  ('post', 3, 4, '👍', now() - interval '4 hours'),
  ('comment', 8, 2, '👍', now() - interval '3 hours'),
  ('comment', 8, 3, '👍', now() - interval '3 hours'),
  ('comment', 8, 4, '👍', now() - interval '3 hours'),
  ('comment', 8, 5, '👍', now() - interval '3 hours'),
  ('comment', 8, 6, '👍', now() - interval '3 hours'),
  ('comment', 9, 1, '👍', now() - interval '1 days'),
  ('comment', 9, 2, '👍', now() - interval '1 days'),
  ('comment', 9, 3, '👍', now() - interval '1 days'),
  ('comment', 9, 4, '👍', now() - interval '1 days'),
  ('post', 4, 1, '👍', now() - interval '6 hours'),
  ('post', 4, 2, '👍', now() - interval '6 hours'),
  ('post', 4, 3, '👍', now() - interval '6 hours'),
  ('post', 4, 4, '👍', now() - interval '6 hours'),
  ('post', 4, 5, '👍', now() - interval '6 hours'),
  ('post', 5, 1, '👍', now() - interval '1 days'),
  ('post', 5, 2, '👍', now() - interval '1 days'),
  ('post', 5, 3, '👍', now() - interval '1 days'),
  ('post', 5, 4, '👍', now() - interval '1 days'),
  ('post', 5, 5, '👍', now() - interval '1 days'),
  ('post', 5, 6, '👍', now() - interval '1 days'),
  ('post', 5, 7, '👍', now() - interval '1 days'),
  ('post', 5, 8, '👍', now() - interval '1 days'),
  ('post', 5, 9, '👍', now() - interval '1 days'),
  ('post', 5, 10, '👍', now() - interval '1 days'),
  ('post', 5, 11, '👍', now() - interval '1 days'),
  ('post', 5, 12, '👍', now() - interval '1 days'),
  ('post', 5, 13, '👍', now() - interval '1 days'),
  ('post', 5, 14, '👍', now() - interval '1 days'),
  ('post', 6, 1, '👍', now() - interval '1 days'),
  ('post', 6, 2, '👍', now() - interval '1 days'),
  ('post', 6, 4, '👍', now() - interval '1 days'),
  ('post', 6, 5, '👍', now() - interval '1 days'),
  ('post', 6, 6, '👍', now() - interval '1 days'),
  ('post', 6, 7, '👍', now() - interval '1 days'),
  ('post', 6, 8, '👍', now() - interval '1 days'),
  ('post', 6, 9, '👍', now() - interval '1 days'),
  ('post', 6, 10, '👍', now() - interval '1 days'),
  ('post', 6, 11, '👍', now() - interval '1 days'),
  ('post', 6, 12, '👍', now() - interval '1 days'),
  ('post', 6, 13, '👍', now() - interval '1 days'),
  ('post', 6, 14, '👍', now() - interval '1 days'),
  ('post', 6, 15, '👍', now() - interval '1 days'),
  ('post', 6, 16, '👍', now() - interval '1 days'),
  ('post', 6, 17, '👍', now() - interval '1 days'),
  ('post', 6, 18, '👍', now() - interval '1 days'),
  ('post', 6, 19, '👍', now() - interval '1 days'),
  ('post', 6, 20, '👍', now() - interval '1 days'),
  ('post', 6, 21, '👍', now() - interval '1 days'),
  ('post', 6, 22, '👍', now() - interval '1 days'),
  ('post', 6, 23, '👍', now() - interval '1 days'),
  ('post', 6, 24, '🔥', now() - interval '1 days'),
  ('post', 6, 25, '🔥', now() - interval '1 days'),
  ('post', 6, 26, '🔥', now() - interval '1 days'),
  ('comment', 10, 1, '👍', now() - interval '1 days'),
  ('comment', 10, 2, '👍', now() - interval '1 days'),
  ('comment', 10, 3, '👍', now() - interval '1 days'),
  ('comment', 10, 5, '👍', now() - interval '1 days'),
  ('comment', 11, 1, '👍', now() - interval '1 days'),
  ('comment', 11, 2, '👍', now() - interval '1 days'),
  ('post', 7, 1, '👍', now() - interval '2 days'),
  ('post', 7, 2, '👍', now() - interval '2 days'),
  ('post', 7, 3, '👍', now() - interval '2 days'),
  ('post', 7, 5, '👍', now() - interval '2 days'),
  ('post', 7, 6, '👍', now() - interval '2 days'),
  ('post', 7, 7, '👍', now() - interval '2 days'),
  ('post', 7, 8, '👍', now() - interval '2 days'),
  ('post', 7, 9, '👍', now() - interval '2 days'),
  ('post', 7, 10, '👍', now() - interval '2 days'),
  ('post', 7, 11, '👍', now() - interval '2 days'),
  ('post', 7, 12, '👍', now() - interval '2 days'),
  ('post', 7, 13, '👍', now() - interval '2 days'),
  ('post', 7, 14, '👍', now() - interval '2 days'),
  ('post', 7, 15, '👍', now() - interval '2 days'),
  ('post', 7, 16, '👍', now() - interval '2 days'),
  ('post', 7, 17, '👍', now() - interval '2 days'),
  ('post', 7, 18, '👍', now() - interval '2 days'),
  ('post', 7, 19, '👍', now() - interval '2 days'),
  ('post', 8, 1, '👍', now() - interval '3 days'),
  ('post', 8, 2, '👍', now() - interval '3 days'),
  ('post', 8, 3, '👍', now() - interval '3 days'),
  ('post', 8, 4, '👍', now() - interval '3 days'),
  ('post', 8, 5, '👍', now() - interval '3 days'),
  ('post', 8, 6, '👍', now() - interval '3 days'),
  ('post', 8, 8, '👍', now() - interval '3 days'),
  ('post', 9, 1, '👍', now() - interval '1 days'),
  ('post', 10, 1, '👍', now() - interval '2 days'),
  ('post', 10, 2, '👍', now() - interval '2 days'),
  ('post', 11, 1, '👍', now() - interval '1 days'),
  ('post', 11, 2, '👍', now() - interval '1 days'),
  ('post', 11, 3, '👍', now() - interval '1 days'),
  ('post', 11, 5, '👍', now() - interval '1 days'),
  ('post', 11, 6, '👍', now() - interval '1 days'),
  ('post', 11, 7, '👍', now() - interval '1 days'),
  ('comment', 12, 1, '👍', now() - interval '1 days'),
  ('comment', 12, 2, '👍', now() - interval '1 days'),
  ('comment', 12, 3, '👍', now() - interval '1 days'),
  ('comment', 12, 4, '👍', now() - interval '1 days'),
  ('comment', 12, 5, '👍', now() - interval '1 days'),
  ('post', 12, 1, '👍', now() - interval '1 days'),
  ('post', 12, 2, '👍', now() - interval '1 days'),
  ('post', 12, 3, '👍', now() - interval '1 days'),
  ('post', 12, 4, '👍', now() - interval '1 days'),
  ('post', 13, 1, '👍', now() - interval '2 days'),
  ('post', 13, 2, '👍', now() - interval '2 days'),
  ('post', 13, 4, '👍', now() - interval '2 days'),
  ('post', 13, 5, '👍', now() - interval '2 days'),
  ('post', 13, 6, '👍', now() - interval '2 days'),
  ('post', 13, 7, '👍', now() - interval '2 days'),
  ('post', 13, 8, '👍', now() - interval '2 days'),
  ('post', 13, 9, '👍', now() - interval '2 days'),
  ('post', 13, 10, '👍', now() - interval '2 days'),
  ('post', 13, 11, '👍', now() - interval '2 days'),
  ('post', 13, 12, '👍', now() - interval '2 days'),
  ('comment', 13, 1, '👍', now() - interval '2 days'),
  ('comment', 13, 2, '👍', now() - interval '2 days'),
  ('comment', 13, 3, '👍', now() - interval '2 days'),
  ('post', 14, 1, '👍', now() - interval '2 days'),
  ('post', 14, 2, '👍', now() - interval '2 days'),
  ('post', 14, 3, '👍', now() - interval '2 days'),
  ('post', 15, 1, '👍', now() - interval '3 days'),
  ('post', 15, 2, '👍', now() - interval '3 days'),
  ('post', 15, 3, '👍', now() - interval '3 days'),
  ('post', 15, 4, '👍', now() - interval '3 days'),
  ('post', 15, 5, '👍', now() - interval '3 days'),
  ('comment', 14, 2, '👍', now() - interval '3 days'),
  ('comment', 14, 3, '👍', now() - interval '3 days'),
  ('comment', 14, 4, '👍', now() - interval '3 days'),
  ('comment', 14, 5, '👍', now() - interval '3 days'),
  ('comment', 14, 6, '👍', now() - interval '3 days'),
  ('comment', 14, 7, '👍', now() - interval '3 days'),
  ('post', 16, 1, '👍', now() - interval '4 days'),
  ('post', 16, 2, '👍', now() - interval '4 days'),
  ('post', 16, 3, '👍', now() - interval '4 days'),
  ('post', 16, 4, '👍', now() - interval '4 days'),
  ('post', 16, 5, '👍', now() - interval '4 days'),
  ('post', 16, 6, '👍', now() - interval '4 days'),
  ('post', 16, 7, '👍', now() - interval '4 days'),
  ('post', 16, 8, '👍', now() - interval '4 days'),
  ('post', 16, 9, '👍', now() - interval '4 days'),
  ('post', 17, 1, '👍', now() - interval '4 days'),
  ('post', 17, 2, '👍', now() - interval '4 days'),
  ('post', 18, 1, '👍', now() - interval '5 days'),
  ('post', 18, 2, '👍', now() - interval '5 days'),
  ('post', 18, 3, '👍', now() - interval '5 days'),
  ('post', 18, 4, '👍', now() - interval '5 days'),
  ('post', 18, 5, '👍', now() - interval '5 days'),
  ('post', 18, 6, '👍', now() - interval '5 days'),
  ('post', 18, 7, '👍', now() - interval '5 days'),
  ('comment', 15, 1, '👍', now() - interval '4 days'),
  ('comment', 15, 2, '👍', now() - interval '4 days'),
  ('comment', 15, 4, '👍', now() - interval '4 days'),
  ('comment', 15, 5, '👍', now() - interval '4 days'),
  ('post', 19, 1, '👍', now() - interval '5 days'),
  ('post', 19, 2, '👍', now() - interval '5 days'),
  ('post', 19, 3, '👍', now() - interval '5 days'),
  ('post', 20, 1, '👍', now() - interval '6 days'),
  ('post', 20, 2, '👍', now() - interval '6 days'),
  ('post', 20, 3, '👍', now() - interval '6 days'),
  ('post', 20, 4, '👍', now() - interval '6 days'),
  ('post', 21, 1, '👍', now() - interval '5 days'),
  ('post', 21, 2, '👍', now() - interval '5 days'),
  ('post', 22, 1, '👍', now() - interval '6 days'),
  ('post', 22, 2, '👍', now() - interval '6 days'),
  ('post', 22, 3, '👍', now() - interval '6 days'),
  ('post', 22, 4, '👍', now() - interval '6 days'),
  ('post', 22, 5, '👍', now() - interval '6 days'),
  ('post', 22, 7, '👍', now() - interval '6 days'),
  ('post', 22, 8, '👍', now() - interval '6 days'),
  ('post', 22, 9, '👍', now() - interval '6 days'),
  ('post', 23, 2, '👍', now() - interval '7 days'),
  ('post', 23, 3, '👍', now() - interval '7 days'),
  ('post', 23, 4, '👍', now() - interval '7 days'),
  ('post', 23, 5, '👍', now() - interval '7 days'),
  ('post', 23, 6, '👍', now() - interval '7 days'),
  ('post', 23, 7, '👍', now() - interval '7 days'),
  ('post', 23, 8, '👍', now() - interval '7 days'),
  ('post', 23, 9, '👍', now() - interval '7 days'),
  ('post', 23, 10, '👍', now() - interval '7 days'),
  ('post', 23, 11, '👍', now() - interval '7 days'),
  ('post', 23, 12, '👍', now() - interval '7 days'),
  ('post', 23, 13, '👍', now() - interval '7 days'),
  ('post', 23, 14, '👍', now() - interval '7 days'),
  ('post', 23, 15, '👍', now() - interval '7 days'),
  ('post', 23, 16, '👍', now() - interval '7 days'),
  ('post', 23, 17, '👍', now() - interval '7 days');

-- 피드백권 소모. 글을 올리는 시점에 나간다. 답이 안 와도 이미 쓴 것이다.
INSERT INTO feedback_pass_use (lounge_id, user_id, post_id, used_at) VALUES
  (1, 2, 3, now() - interval '4 hours'),
  (1, 13, 9, now() - interval '1 days'),
  (1, 10, 10, now() - interval '2 days'),
  (1, 5, 21, now() - interval '5 days');

-- id 를 직접 넣었으므로 시퀀스를 다음 값으로 옮겨 둔다.
SELECT setval(pg_get_serial_sequence('lounge','id'),   (SELECT max(id) FROM lounge));
SELECT setval(pg_get_serial_sequence('category','id'), (SELECT max(id) FROM category));
SELECT setval(pg_get_serial_sequence('post','id'),     (SELECT max(id) FROM post));
SELECT setval(pg_get_serial_sequence('comment','id'),  (SELECT max(id) FROM comment));

-- 파생 카운터를 실제 행 수로 맞춘다. 시드가 어긋나지 않았는지 확인하는 셈이기도 하다.
UPDATE post SET
  comment_count  = (SELECT count(*) FROM comment c WHERE c.post_id = post.id AND c.deleted_at IS NULL),
  reaction_count = (SELECT count(*) FROM reaction r WHERE r.target_kind = 'post' AND r.target_id = post.id);

UPDATE comment SET
  reaction_count = (SELECT count(*) FROM reaction r WHERE r.target_kind = 'comment' AND r.target_id = comment.id);

COMMIT;

